const supabaseDatabaseUrl = 'https://zmcohvajrzxmartfcasr.supabase.co';
const supabaseAnon =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptY29odmFqcnp4bWFydGZjYXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA1ODU5MTUsImV4cCI6MjAyNjE2MTkxNX0.3bzGPV0Oo6xYzqolJYlbHzmOTEMsTbSm2vosI6BXlZs';
