const supabaseDatabaseUrl = 'https://qpowmvphtooxukcwefyr.supabase.co';
const supabaseAnon =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmdW5wbmxiYXlvYm52c3BtamRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc0MTU2MjEsImV4cCI6MjA0Mjk5MTYyMX0.t3fWH8komiB6nfY39l_LUBOXcoXTH4PWRQcgShCJ7s8';
